name: Deploy
on:
  push:
    tags:
      - '*'

permissions:
  contents: write
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
      - name: Build distribution
        run: ./gradlew :adapter:distZip
      - name: Create release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          name: Version ${{ github.ref }}
          draft: false
          prerelease: false
          files: |
            ./adapter/build/distributions/adapter.zip
